# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73b11c686a5d4409dbce1e8a7a8004be83cebc1659f249bb69c48989a52c5d79a490e8b60387e8a841c1e316501dc183421ef08a4badf93913ef4c512a3e4dca

test:
  secret_key_base: 77de71d03adb3c68f4ff514723de60519cee382f3e7c463fcb3e2089a41629bcfc6db7a682c807234dbfd6e28cb90ec319cc61721e9448e94cfbab646a1a2780

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
